In [2]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
fashion_mnist = datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))
# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

4423680/4422102 [==============================] - 0s 0us/step


In [8]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1))) # the 1st 2d-convolutional layer
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 3, 3, 64)          36928     
_________________________________________________________________
flatten (Flatten)            (None, 576)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)               

In [20]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=5,batch_size=64)

test_loss, test_acc = model.evaluate(test_images, test_labels)

print(test_acc)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 21s 352us/sample - loss: 0.1006 - accuracy: 0.9617
Epoch 2/5
60000/60000 [==============================] - 21s 346us/sample - loss: 0.0830 - accuracy: 0.9691
Epoch 3/5
60000/60000 [==============================] - 20s 336us/sample - loss: 0.0745 - accuracy: 0.9716
Epoch 4/5
60000/60000 [==============================] - 21s 345us/sample - loss: 0.0705 - accuracy: 0.9728
Epoch 5/5
10000/10000 [==============================] - 1s 126us/sample - loss: 0.3799 - accuracy: 0.9084
0.9084


In [21]:
from sklearn.metrics import confusion_matrix
import numpy as np
test_pred = model.predict(test_images)
conf = confusion_matrix(test_labels, np.argmax(test_pred, axis=1))
print(conf)

[[876   1  20  18   4   0  79   0   2   0]
 [  4 979   0  10   2   0   3   0   2   0]
 [ 17   1 890   8  33   0  51   0   0   0]
 [ 26   8  11 899  26   0  28   0   2   0]
 [  1   0  78  23 844   0  49   0   5   0]
 [  0   0   0   0   0 980   0  13   0   7]
 [112   0  73  25  55   0 732   0   3   0]
 [  0   0   0   0   0  11   0 945   1  43]
 [  8   0   4   4   3   3   9   0 966   3]
 [  1   0   0   0   0   4   0  22   0 973]]
